fixed issue from commit 3f772c0
expm1.c:363:14: error: unused variable 'res' [-Werror,-Wunused-variable]
  363 |       double res = __builtin_fma(0x1p-54, __builtin_fabs(x), x);
      |              ^~~